# Generated by Django 6.0.5 on 2026-06-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "constructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.company",
                    ),
                ),
            ],
            options={
                "ordering": ["constructor", "name"],
            },
        ),
        migrations.CreateModel(
            name="GraphicsCard",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graphics Card",
                "verbose_name_plural": "Graphics Cards",
                "ordering": ["constructor", "name"],
            },
            bases=("api.component",),
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.component",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "N/A"),
                            (1, "SDR"),
                            (2, "DDR1"),
                            (3, "DDR2"),
                            (4, "DDR3"),
                            (5, "DDR4"),
                            (6, "DDR5"),
                        ]
                    ),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("frequency", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "Memory Stick",
                "verbose_name_plural": "Memory Sticks",
                "ordering": ["constructor", "name"],
            },
            bases=("api.component",),
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.component",
                    ),
                ),
                (
                    "network_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Ethernet"), (1, "Wi-Fi")]
                    ),
                ),
                ("speed", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "Network Connection",
                "verbose_name_plural": "Network Connections",
                "ordering": ["constructor", "name"],
            },
            bases=("api.component",),
        ),
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.component",
                    ),
                ),
                (
                    "architecture",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "x86 (32-bit)"), (1, "AMD64 (64-bit)"), (2, "ARM")]
                    ),
                ),
                ("frequency", models.PositiveBigIntegerField()),
                ("core_count", models.PositiveSmallIntegerField()),
            ],
            bases=("api.component",),
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.component",
                    ),
                ),
                (
                    "storage_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "HDD"), (1, "SSD"), (2, "NVMe"), (3, "eMMC")]
                    ),
                ),
                ("size", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "Storage Device",
                "verbose_name_plural": "Storage Devices",
                "ordering": ["constructor", "name"],
            },
            bases=("api.component",),
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(choices=[("ldlc", "LDLC")], max_length=100)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("model_number", models.CharField(blank=True, max_length=150)),
                ("serial_number", models.CharField(blank=True, max_length=150)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("laptop", "Laptop"),
                            ("rack", "Rack"),
                            ("mini", "Mini PC"),
                            ("tablet", "Tablet"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.company",
                    ),
                ),
            ],
            options={
                "ordering": ["constructor", "model_number", "serial_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComputerGraphicsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.computer"
                    ),
                ),
                (
                    "graphics_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.graphicscard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="graphics_card",
            field=models.ManyToManyField(
                blank=True, through="api.ComputerGraphicsCard", to="api.graphicscard"
            ),
        ),
        migrations.CreateModel(
            name="ComputerMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.computer"
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.memory"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="memory",
            field=models.ManyToManyField(
                blank=True, through="api.ComputerMemory", to="api.memory"
            ),
        ),
        migrations.CreateModel(
            name="ComputerNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.computer"
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.network"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="network",
            field=models.ManyToManyField(
                blank=True, through="api.ComputerNetwork", to="api.network"
            ),
        ),
        migrations.CreateModel(
            name="ComputerProcessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.computer"
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.processor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="processors",
            field=models.ManyToManyField(
                blank=True, through="api.ComputerProcessor", to="api.processor"
            ),
        ),
        migrations.CreateModel(
            name="ComputerStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.computer"
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.storage"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="storage",
            field=models.ManyToManyField(
                blank=True, through="api.ComputerStorage", to="api.storage"
            ),
        ),
    ]
