# Generated by Django 6.0.3 on 2026-03-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('constructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('vram_size', models.PositiveBigIntegerField()),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('size', models.PositiveBigIntegerField()),
                ('frequency', models.PositiveBigIntegerField()),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('network_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('wifi', 'Wi-Fi')], max_length=10)),
                ('speed', models.PositiveBigIntegerField()),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('architecture', models.CharField(choices=[('x86', 'x86 (32-bit)'), ('x86-64', 'x86-64 (64-bit)'), ('arm', 'ARM')], max_length=10)),
                ('frequency', models.PositiveBigIntegerField()),
                ('core_count', models.PositiveSmallIntegerField()),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('storage_type', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD'), ('nvme', 'NVMe'), ('eMMC', 'eMMC')], max_length=10)),
                ('size', models.PositiveBigIntegerField()),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
                ('graphics_card', models.ManyToManyField(to='api.graphicscard')),
                ('memory', models.ManyToManyField(to='api.memory')),
                ('network', models.ManyToManyField(to='api.network')),
                ('processors', models.ManyToManyField(to='api.processor')),
                ('storage', models.ManyToManyField(to='api.storage')),
            ],
        ),
    ]
