# Generated by Django 6.0.5 on 2026-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="type",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("sdr", "SDR"),
                    ("ddr1", "DDR1"),
                    ("ddr2", "DDR2"),
                    ("ddr3", "DDR3"),
                    ("ddr4", "DDR4"),
                    ("ddr5", "DDR5"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("hdd", "HDD"),
                    ("ssd", "SSD"),
                    ("nvme", "NVMe"),
                    ("emmc", "eMMC"),
                ],
                max_length=100,
            ),
        ),
    ]
