# Generated by Django 6.0.3 on 2026-03-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicscard',
            name='vram_size',
        ),
    ]
