# Generated by Django 6.1.1 on 2026-09-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('form_factor', models.CharField(choices=[('atx', 'ATX'), ('sfx', 'SFX'), ('tfx', 'TFX'), ('eps', 'EPS')], max_length=25)),
                ('wattage', models.PositiveIntegerField()),
                ('rating', models.CharField(choices=[('80plus', '80 PLUS'), ('80plusbronze', '80 PLUS Bronze'), ('80plussilver', '80 PLUS Silver'), ('80plusgold', '80 PLUS Gold'), ('80plusplatinum', '80 PLUS Platinum'), ('80plustitanium', '80 PLUS Titanium')], max_length=25)),
            ],
            options={
                'verbose_name': 'Power Supply Unit',
                'ordering': ['constructor', 'name'],
            },
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='ComputerPowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.computer')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.powersupply')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='power_supply',
            field=models.ManyToManyField(blank=True, through='api.ComputerPowerSupply', to='api.powersupply'),
        ),
    ]
