# Generated by Django 6.0.3 on 2026-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_graphicscard_vram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
