# Generated by Django 5.2.8 on 2025-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='components',
            field=models.ManyToManyField(to='api.component'),
        ),
    ]
