# Generated by Django 5.2.8 on 2025-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computer_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('O', 'Other')], default='Other', max_length=3),
        ),
    ]
