# Generated by Django 6.0.5 on 2026-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_memory_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphicscard",
            name="vram_size",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
