# Generated by Django 6.0.3 on 2026-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_computer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['constructor', 'name']},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['constructor', 'model_number', 'serial_number', 'name']},
        ),
        migrations.AlterModelOptions(
            name='graphicscard',
            options={'ordering': ['constructor', 'name'], 'verbose_name': 'Graphics Card', 'verbose_name_plural': 'Graphics Cards'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['constructor', 'name'], 'verbose_name': 'Memory Stick', 'verbose_name_plural': 'Memory Sticks'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['constructor', 'name'], 'verbose_name': 'Network Connection', 'verbose_name_plural': 'Network Connections'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['constructor', 'name'], 'verbose_name': 'Storage Device', 'verbose_name_plural': 'Storage Devices'},
        ),
        migrations.AddField(
            model_name='component',
            name='serial_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='computer',
            name='format',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('rack', 'Rack-Mounted'), ('mini', 'Mini PC'), ('tablet', 'Tablet')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
