# Generated by Django 5.2.8 on 2025-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('OTH', 'Other')], default='Other', max_length=3),
        ),
    ]
