# Generated by Django 6.0.5 on 2026-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_graphicscard_vram_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="network_type",
            field=models.CharField(
                choices=[("eth", "Ethernet"), ("wifi", "Wi-Fi")], max_length=100
            ),
        ),
    ]
