# Generated by Django 6.0.3 on 2026-03-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_component_options_alter_computer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='serial_number',
        ),
    ]
