# Generated by Django 6.0.3 on 2026-03-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_component_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='site',
            field=models.CharField(choices=[('ldlc', 'LDLC')], default='ldlc', max_length=15),
            preserve_default=False,
        ),
    ]
