# Generated by Django 6.1.1 on 2026-09-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_network_network_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='storage_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='computer',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
