# Generated by Django 6.0 on 2026-01-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_component_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('core_count', models.SmallIntegerField(verbose_name='Number of cores')),
            ],
            bases=('api.component',),
        ),
        migrations.RemoveField(
            model_name='component',
            name='type',
        ),
    ]
