# Generated by Django 6.0 on 2026-01-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_processor_remove_component_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('kind', models.CharField(choices=[('H', 'HDD'), ('S', 'SSD')], max_length=1)),
                ('size', models.PositiveBigIntegerField(verbose_name='Capacity')),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('kind', models.CharField(choices=[('1', 'DDR1'), ('2', 'DDR2'), ('3', 'DDR3'), ('4', 'DDR4'), ('5', 'DDR5')], max_length=1)),
                ('size', models.PositiveBigIntegerField(verbose_name='Capacity')),
                ('speed', models.PositiveBigIntegerField(verbose_name='Speed')),
            ],
            bases=('api.component',),
        ),
        migrations.AlterField(
            model_name='processor',
            name='core_count',
            field=models.PositiveSmallIntegerField(verbose_name='Number of cores'),
        ),
    ]
