# Generated by Django 6.0.3 on 2026-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_computer_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='processors',
            field=models.ManyToManyField(blank=True, to='api.processor'),
        ),
    ]
