# Generated by Django 6.0.3 on 2026-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_computer_processors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='graphics_card',
            field=models.ManyToManyField(blank=True, to='api.graphicscard'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.ManyToManyField(blank=True, to='api.memory'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='network',
            field=models.ManyToManyField(blank=True, to='api.network'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.ManyToManyField(blank=True, to='api.storage'),
        ),
    ]
