# Generated by Django 6.0.3 on 2026-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_computer_graphics_card_alter_computer_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='site',
            field=models.CharField(choices=[(0, 'LDLC')], max_length=15),
        ),
    ]
