# Generated by Django 6.0.3 on 2026-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_computer_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='format',
            field=models.CharField(choices=[(0, 'Desktop'), (1, 'Laptop'), (2, 'Rack'), (3, 'Mini PC'), (4, 'Tablet')], max_length=15),
        ),
    ]
