# Generated by Django 6.0.3 on 2026-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_computer_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Desktop'), (1, 'Laptop'), (2, 'Rack'), (3, 'Mini PC'), (4, 'Tablet')]),
        ),
        migrations.AlterField(
            model_name='computer',
            name='site',
            field=models.PositiveSmallIntegerField(choices=[(0, 'LDLC')]),
        ),
    ]
