# Generated by Django 6.0.3 on 2026-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_computer_format_alter_computer_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, 'SDR'), (2, 'DDR1'), (3, 'DDR2'), (4, 'DDR3'), (5, 'DDR4'), (6, 'DDR5')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='network_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ethernet'), (1, 'Wi-Fi')]),
        ),
        migrations.AlterField(
            model_name='processor',
            name='architecture',
            field=models.PositiveSmallIntegerField(choices=[(0, 'x86 (32-bit)'), (1, 'AMD64 (64-bit)'), (2, 'ARM')]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'HDD'), (1, 'SSD'), (2, 'NVMe'), (3, 'eMMC')]),
        ),
    ]
