# Generated by Django 6.0.5 on 2026-06-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_memory_type_alter_network_network_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputerGraphicsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.computer"
                    ),
                ),
                (
                    "graphics_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.graphicscard",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="computer",
            name="graphics_card",
            field=models.ManyToManyField(
                blank=True, through="api.ComputerGraphicsCard", to="api.graphicscard"
            ),
        ),
    ]
